# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-29 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='ltime',
        ),
        migrations.AddField(
            model_name='lesson',
            name='ltime',
            field=models.ManyToManyField(blank=True, db_column='ltime', null=True, related_name='ltime', to='app.LessonTime', verbose_name='\u4e0a\u8bfe\u65f6\u95f4'),
        ),
    ]
